**Matrix** for iPhone sales in different regions in USA

In [14]:
import numpy as np

# Sales Data for Quarter 1(Matrix 1)
#Rows represent different products, col represent different regions

q1 = np.array([
    [200, 220,250], #Product A
    [150,180,210], #Product B
    [300,330,360] #Product C
])

q2 = np.array([
    [209, 231,259], #Product A
    [155,192,222], #Product B
    [310,340,375] #Product C
])

In [15]:
q1+q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [16]:
(q2-q1)*100/q1


array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [17]:
prices = np.array([
    [10, 12,11], #Product A
    [14,11,10], #Product B
    [13,11,12] #Product C
])

In [18]:
revenue = (q1+q2)*prices
revenue

array([[4090, 5412, 5599],
       [4270, 4092, 4320],
       [7930, 7370, 8820]])

In [19]:
discount =  (q1+q2)*.2
discount

array([[ 81.8,  90.2, 101.8],
       [ 61. ,  74.4,  86.4],
       [122. , 134. , 147. ]])

In [20]:
net_revenue = revenue - discount
net_revenue

array([[4008.2, 5321.8, 5497.2],
       [4209. , 4017.6, 4233.6],
       [7808. , 7236. , 8673. ]])

In [21]:
np.sum(net_revenue)

np.float64(51004.4)

In [24]:
features = np.array([
    [2000, 3], # house 1: 2000 sqpt, 3 bedrooms
    [1500, 2]
])

weights = np.array([150, 50000])
2000 * 150 + 3* 50000

450000

In [25]:
np.dot(features, weights)

array([450000, 325000])

In [26]:
np.cross(features, weights)

/var/folders/kp/_lmry29d6xj13k1_dsxljwtr0000gn/T/ipykernel_23775/1042894610.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(features, weights)


array([99999550, 74999700])