In [8]:
import numpy as np
rev = np.array([[12,15,14], [13,15,16]], dtype = np.float64)
rev.ndim

2

In [9]:
rev.shape

(2, 3)

In [10]:
rev[1,2]

np.float64(16.0)

In [7]:
rev[1,2] =100
rev

array([[ 12,  15,  14],
       [ 13,  15, 100]])

In [13]:
rev.dtype

dtype('float64')

In [14]:
np.sort(rev, axis=None)

array([12., 13., 14., 15., 15., 16.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
np.linspace(20,100,8)

array([ 20.        ,  31.42857143,  42.85714286,  54.28571429,
        65.71428571,  77.14285714,  88.57142857, 100.        ])

In [28]:
rev.ravel()

array([12., 15., 14., 13., 15., 16.])

In [27]:
rev.flatten()

array([12., 15., 14., 13., 15., 16.])

In [31]:
rev.reshape(3,2)

array([[12., 15.],
       [14., 13.],
       [15., 16.]])

In [32]:
rev.min()

np.float64(12.0)

In [34]:
rev.max()

np.float64(16.0)

In [37]:
rev.sum(axis=0) #Axis 0 is summing vertically

array([25., 30., 30.])

In [38]:
rev.sum(axis=1) #Axis 1 is summing horizontally

array([41., 44.])

In [39]:
np.sqrt(rev)

array([[3.46410162, 3.87298335, 3.74165739],
       [3.60555128, 3.87298335, 4.        ]])

In [40]:
np.std(rev)

np.float64(1.3437096247164249)