In [1]:
import numpy as np

a = np.array([1,2,3,5,6,7])

In [2]:
a[0:3]

array([1, 2, 3])

In [3]:
a[4:]

array([6, 7])

In [4]:
a[-2]

np.int64(6)

In [5]:
b = np.array([
    [1,5,6,7],
    [3,5,6,7],
    [1,2,3,7]
])

In [6]:
b[1,]

array([3, 5, 6, 7])

In [7]:
b[1,3]

np.int64(7)

In [8]:
b[2,0:3]

array([1, 2, 3])

**Stack**

In [23]:
c= np.array([
    [101, "Minhaz", "SWE"],
    [102, "Monir", "CE"],
    [103, "Kamrul", "TA"]
])

d= np.array([
    [101, 28, "Sylhet"],
    [102, 31, "Dhaka"],
    [103, 34, "CTG"]
])

In [24]:
np.hstack((c,d))

array([['101', 'Minhaz', 'SWE', '101', '28', 'Sylhet'],
       ['102', 'Monir', 'CE', '102', '31', 'Dhaka'],
       ['103', 'Kamrul', 'TA', '103', '34', 'CTG']], dtype='<U21')

In [25]:
e= np.array([
    [104, "Rahul", "SWE"],
    [105, "Harun", "CE"],
])

In [27]:
f = np.vstack((c,e))

In [28]:
f

array([['101', 'Minhaz', 'SWE'],
       ['102', 'Monir', 'CE'],
       ['103', 'Kamrul', 'TA'],
       ['104', 'Rahul', 'SWE'],
       ['105', 'Harun', 'CE']], dtype='<U21')

In [33]:
np.hsplit(f, [2])

[array([['101', 'Minhaz'],
        ['102', 'Monir'],
        ['103', 'Kamrul'],
        ['104', 'Rahul'],
        ['105', 'Harun']], dtype='<U21'),
 array([['SWE'],
        ['CE'],
        ['TA'],
        ['SWE'],
        ['CE']], dtype='<U21')]

In [34]:
np.vsplit(f, [2])

[array([['101', 'Minhaz', 'SWE'],
        ['102', 'Monir', 'CE']], dtype='<U21'),
 array([['103', 'Kamrul', 'TA'],
        ['104', 'Rahul', 'SWE'],
        ['105', 'Harun', 'CE']], dtype='<U21')]

In [35]:
monthly_sales = np.array([30,25,52,23,53,65])

In [36]:
result = monthly_sales >32

In [37]:
result

array([False, False,  True, False,  True,  True])

In [38]:
monthly_sales[result]

array([52, 53, 65])